spring:
  datasource:
    username: root
    password: Qyq30631
    url: jdbc:mysql://106.55.92.181:3306/Test
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mapper/*.xml
